// src/FoodData.js
const foodItems = [
  {
    id: 1,
    name: "Fried-Rice",
    type: "Veg",
    price: 120,
    image: "/ai-food-management/fimage/fried-rice.jpg",
    availableQuantity: null,
    description: "Delicious fried rice with fresh vegetables.",
    category: "Main Course",
  },
  { 
    id: 16, 
    name: "Double Ka Meetha", 
    price: 130, 
    image: "/ai-food-management/fimage/doublemeetha.jpeg", 
    category: "Dessert", 
    description: "Bread pudding in saffron milk",
    type: "Veg"
  },
  { 
    id: 17, 
    name: "Irani Chai & Osmania Biscuit", 
    price: 100, 
    image: "/ai-food-management/fimage/iranichai.jpeg", 
    category: "Beverages", 
    description: "Traditional Hyderabadi tea with special biscuits",
    type: "Veg"
  },
  {
    id: 2,
    name: "Chicken Biryani",
    type: "Non-Veg",
    price: 180,
    image: "/ai-food-management/fimage/biryani.jpg",
    availableQuantity: null,
    description: "Authentic Hyderabadi chicken biryani with rich spices.",
    category: "Main Course",
  },
  {
    id: 3,
    name: "Paneer Butter Masala",
    type: "Veg",
    price: 150,
    image: "/ai-food-management/fimage/paneer.jpeg",
    availableQuantity: null,
    description: "Soft paneer cubes cooked in rich buttery tomato gravy.",
    category: "Curry",
  },
  {
    id: 4,
    name: "Fish Curry",
    type: "Non-Veg",
    price: 200,
    image: "/ai-food-management/fimage/fish.jpeg",
    availableQuantity: null,
    description: "Traditional spicy fish curry made with coconut and tamarind.",
    category: "Curry",
  },
  {
    id: 5,
    name: "Gulab Jamun",
    type: "Veg",
    price: 60,
    image: "/ai-food-management/fimage/gulab-jamun.jpeg",
    availableQuantity: null,
    description: "Soft and sweet dessert balls soaked in sugar syrup.",
    category: "Dessert",
  },
  {
    id: 6,
    name: "Vegetable Noodles",
    type: "Veg",
    price: 130,
    image: "/ai-food-management/fimage/noodles.jpg",
    availableQuantity: null,
    description: "Stir-fried noodles with fresh vegetables and soy sauce.",
    category: "Main Course",
  },
  {
    id: 7,
    name: "Mutton Biryani",
    type: "Non-Veg",
    price: 220,
    image: "/ai-food-management/fimage/mbiryani.jpg",
    availableQuantity: null,
    description: "Flavorful mutton biryani with aromatic spices and herbs.",
    category: "Main Course",
  },
  {
    id: 8,
    name: "Kadai Paneer",
    type: "Veg",
    price: 160,
    image: "/ai-food-management/fimage/kpaneer.jpg",
    availableQuantity: null,
    description: "Paneer cooked with bell peppers and kadai masala.",
    category: "Curry",
  },
  {
    id: 9,
    name: "Prawn Curry",
    type: "Non-Veg",
    price: 240,
    image: "/ai-food-management/fimage/Prawns.jpg",
    availableQuantity: null,
    description: "Spicy prawn curry with coconut milk and traditional spices.",
    category: "Curry",
  },
  {
    id: 10,
    name: "Rasgulla",
    type: "Veg",
    price: 50,
    image: "/ai-food-management/fimage/rasgulla.jpg",
    availableQuantity: null,
    description: "Soft and spongy cottage cheese balls in light sugar syrup.",
    category: "Dessert",
  },
  {
    id: 11,
    name: "Jeera Rice",
    type: "Veg",
    price: 100,
    image: "/ai-food-management/fimage/jeera-rice.jpg",
    availableQuantity: null,
    description: "Fragrant basmati rice tempered with cumin seeds.",
    category: "Main Course",
  },
  {
    id: 12,
    name: "Egg Biryani",
    type: "Non-Veg",
    price: 140,
    image: "/ai-food-management/fimage/egg-biryani.jpg",
    availableQuantity: null,
    description: "Delicious biryani made with boiled eggs and aromatic spices.",
    category: "Main Course",
  },
  {
    id: 13,
    name: "Palak Paneer",
    type: "Veg",
    price: 145,
    image: "/ai-food-management/fimage/palak-paneer.jpg",
    availableQuantity: null,
    description: "Paneer cubes in creamy spinach gravy with mild spices.",
    category: "Curry",
  },
  {
    id: 14,
    name: "Chicken Curry",
    type: "Non-Veg",
    price: 170,
    image: "/ai-food-management/fimage/chicken-curry.jpg",
    availableQuantity: null,
    description: "Classic chicken curry with onion-tomato based gravy.",
    category: "Curry",
  },
  {
    id: 15,
    name: "Rasmalai",
    type: "Veg",
    price: 70,
    image: "/ai-food-management/fimage/rasmalai.jpg",
    availableQuantity: null,
    description: "Soft cheese patties soaked in sweetened, thickened milk.",
    category: "Dessert",
  },
];

export default foodItems;